services:
  frontend:
    container_name: gaeb-frontend-dev
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    environment:
      VUE_APP_API_PATH: "${VUE_APP_API_PATH}"

  backend:
    container_name: gaeb-backend-dev
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://*:5007"
      ConnectionStrings__PostgresqlDbConnection: "${POSTGRES_CONNECTION_STRING}"
      JwtConfig__Secret: "${JWT_SECRET}"
      
    ports:
      - "5007:5007"

  db:
    container_name: gaeb-database-dev
    restart: unless-stopped
    image: postgres:18.1-alpine
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - "5432:5432"

