/* tslint:disable */
/* eslint-disable */
/**
 * API 0.1.1-beta0219
 * Dangl.OpenCDE API Specification
 *
 * The version of the OpenAPI document: 0.1.1-beta0219
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

